### ISSUE TITLE
Convert Config File to JSON

### ISSUE THREAD

**Issue by Velocity23** [va-net/flare#109]
**Is your feature request related to a problem? Please describe.**
It's not easy to work with the config.php file as-is. Replacements, additions and changes are all a pain.

**Describe the solution you'd like**
Change to JSON format

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gayblackpeoplearepoo** [comment]
I hate asians because they are colonising Australia

**Comment by gayblackpeoplearepoo** [comment]
fuck

**Comment by gayblackpeoplearepoo** [comment]
fuck

**Comment by Velocity23** [comment]
Not doable
