### ISSUE TITLE
Import from phpVMS CSV Format

### ISSUE THREAD

**Issue by Velocity23** [va-net/flare#129]
**Is your feature request related to a problem? Please describe.**
There's currently no option to import from phpVMS format, this makes it hard to move from one Crew Center to another

**Describe the solution you'd like**
Option to import CSV from phpVMS format as well as export to a FlareJSON format (specs TBC)

**Describe alternatives you've considered**
N/A

**Additional context**
Aircraft Template: https://slack-files.com/T0164LFP48M-F018WJXS0QM-797282ba64
Airports Template: https://slack-files.com/T0164LFP48M-F01945XLHU4-26b27ad8f6
Routes Template: https://slack-files.com/T0164LFP48M-F018R8D2G22-29908d69d0

**Comment by velocity23** [comment]
Hey, unfortunately there's no export function at the moment because the CSV import is really a bit of a hack. There is, however, a new routes template available at https://drive.google.com/file/d/1EJQYOQVLymL8Jvn5y-MS-lVTb32Sn90D/view?usp=sharing.

**Comment by vegaskukichyo** [comment]
Understood, and I thank you for the assistance.
