### ISSUE TITLE
Hubs for Pilot Consolidation

### ISSUE THREAD

**Issue by TheWheelDaddy** [va-net/flare#155]
An added Feature found on most CC platforms to group pilots by hubs or bases to consolidate PIREP filing and gain control over large pilot population.

The function can be found on phpvms platforms.

SWVA utilizes bases or hubs to help with the work load of over a 100 pilots being managed along with their PIREPs. 

We also host internal hub competitions monthly and rewards for hub competitions.

This feature request is to further our awesome base consolidation on flare! We love it so far! Thank you!

**Comment by Velocity23** [comment]
Might be able to get this done before V2, stand by

**Comment by Velocity23** [comment]
This will have come come as a plugin (#194). Closing for now.
