### ISSUE TITLE
VANet Gold isn't Recognized on Pages

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#161]
**Describe the bug**  
I am told that we have VANet gold yet flare states that we need to get VANet gold to use certain features.  
**To Reproduce**  

1.  Log In
2.  Attempt to Access a Gold Feature

**Expected behavior**  
Features that require VANet Gold are available and do not prompt you to purchase gold

**Screenshots**  
N/A

**Comment by Velocity23** [comment]
Fixed in the next one (hopefully)
