### ISSUE TITLE
Adding Routes

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#162]
**Describe the bug**
When I add a route to our Route Database, I get a green bar saying Added Successfully but it then shows 0 out of 0 routes in our database.

**To Reproduce**
1. Go to 'Manage Routes'
2. Click on 'Add Route'
3. Fill in information
4. Submit form
5. See error

**Expected behavior**
I expected the route to be added to my set of routes

**Screenshots**
Screenshot not necessary

**Additional context**
I have had other issues with my Crew Center so it is possible mine is just messed up

**Comment by samdog2727** [comment]
Something interesting that I have just noticed. When I go to VA Statistics, it says I have 4 Routes (the number of times I tried to input that route but with different variables) but I can't find the actual 4 routes anywhere else.

**Comment by Velocity23** [comment]
I can't reproduce this :/

**Comment by Velocity23** [comment]
Alright found the issue, the aircraft ID isn't being set properly in the DB

**Comment by Velocity23** [comment]
Fixed in the next update
