### ISSUE TITLE
Route of the Week

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#163]
**Is your feature request related to a problem? Please describe.**
My feature is not really related to a problem. 

**Describe the solution you'd like**
I would like the ability to make certain routes visible as a route of the week, this could be by having it bolded or a different color. This would also make it so the Flare Staff member could change if any rank could fly that route or not. 

**Describe alternatives you've considered**
I don't know if this is possible it's just an idea.

**Additional context**
It would be cool to have as many IF VA/VOs have a Route of the Week system. I understand that this could have too many variables as the rules for ROTWs change per VA/VO but it's just a thought.

**Comment by Velocity23** [comment]
This won’t be added to the main version of Flare as @rebal15 offers a full ROTW system to his Patreon supporters.
