### ISSUE TITLE
Aircraft Selection w/Liveries

### ISSUE THREAD

**Issue by TheWheelDaddy** [va-net/flare#164]
When picking an aircraft to add the list of all added aircraft does not list the Livery therefore leaving the user to not know which aircraft they are selecting. 

Next to an added aircraft in the list could the livery be put next to the aircraft's model:

![image](https://user-images.githubusercontent.com/71365826/93397949-41937680-f840-11ea-8310-806fdf79ac3b.png)

As seen in the photo it is currently only the aircraft models listed while they all are a different livery. It is not clear which livery they each are as the livery cannot be seen in the list. 

Can we change that for next push?

Thank you!

**Comment by Velocity23** [comment]
Fixed in the next one. Livery names in the admin panel are hidden on mobile so the table isn't too wide.d

**Comment by Velocity23** [comment]
Still an issue in PIREP Filing
