### ISSUE TITLE
No Events

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#167]
**Describe the bug**
After logging into Flare, I go to the events and there are none there even though I created them. When I create a new event, then the new event along with the other events show up but with no information for variables.

**To Reproduce**
1. Login to Flare
2. Go to 'Events' on the Pilot Panel
3. See error (No events are there)
4. Scroll down to 'Manage Events' in Administration
5. Create a new event
6. Go back to 'Events' on the Pilot Panel
7. See all events but with no variable data

**Expected behavior**
I expected to be able to see my events when I logged in.

**Screenshots**
There is really nothing to see (yes, this is a joke)

**Additional context**
Lots of Events issues recently.

**Comment by Velocity23** [comment]
I think this might be fixed when I fix #166 so stand by

**Comment by Velocity23** [comment]
Unable to reproduce, probably a rate limiting issue
