### ISSUE TITLE
Cannot See Events

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#168]
**Describe the bug**
After creating an event, I can't see the Events tab on the pilot panel.

**To Reproduce**
1. Go to 'Manage Events'
2. Click on 'New Event'
3. Fill out variables
4. Look for 'Events' tab on Pilot Panel
5. See error/Can't see it

**Expected behavior**
I expected to be able to see the Events tab.

**Screenshots**
![Screen Shot 2020-09-17 at 9 21 51 AM](https://user-images.githubusercontent.com/71337097/93475989-464f3d80-f8c7-11ea-90af-c80fd9c028b6.png)

**Additional context**
As mentioned before, lots of event problems.

**Comment by Velocity23** [comment]
This is to do with rate limiting on VANet’s end, basically you’re doing stuff too quickly. I’ll increase the limit but it should fix itself after 60 seconds.
