### ISSUE TITLE
Error when Editing Aircraft 

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#169]
**Describe the bug**
You cannot change the rank requirements for aircraft on page 2 or later.

**To Reproduce**
1. Go to 'Manage Fleet'
2. Go to Page 2 or later
3. Click on 'Edit' for any aircraft

**Expected behavior**
A screen to pop-up like it does on page 1.

**Screenshots**
Not necessary

**Additional context**
Kai can log-in to ours to check it out.

**Comment by Velocity23** [comment]
Issue with datatables, just need to rename this `data-` attribute

**Comment by samdog2727** [comment]
@Velocity23 , This will be fixed in Beta 11?

**Comment by Velocity23** [comment]
Yes

**Comment by Velocity23** [comment]
Fix coming in the next one
