### ISSUE TITLE
The 0 Server

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#170]
**Describe the bug**
When you don't force a server, the PiREP asks you to spawn on 0 server.

**To Reproduce**
1. Go to 'PIREP'
2. See error

**Expected behavior**
Give a clear server to spawn in at.

**Screenshots**
![Screen Shot 2020-09-17 at 6 11 42 PM](https://user-images.githubusercontent.com/71337097/93533836-d6b27000-f911-11ea-9d72-e992306d6124.png)

**Additional context**
Nope :)

**Comment by Velocity23** [comment]
Only works when the Force Server option is set to None.
