### ISSUE TITLE
Editing In Lists

### ISSUE THREAD

**Issue by TheWheelDaddy** [va-net/flare#174]
I have found that in all lists:
User list
Route List
Fleet List

You can only edit each individual item on the first page. On every page after the first page you cannot.

![image](https://user-images.githubusercontent.com/71365826/93722751-a90e3680-fb5e-11ea-99ef-888fdbcd7f88.png)
![image](https://user-images.githubusercontent.com/71365826/93722753-aca1bd80-fb5e-11ea-82f2-97dcb78fc129.png)
![image](https://user-images.githubusercontent.com/71365826/93722757-b0cddb00-fb5e-11ea-9bfe-a666d78f05a0.png)
![image](https://user-images.githubusercontent.com/71365826/93722758-b4616200-fb5e-11ea-953b-18d902e2596f.png)
![image](https://user-images.githubusercontent.com/71365826/93722760-b88d7f80-fb5e-11ea-8257-2c88aafd232e.png)
![image](https://user-images.githubusercontent.com/71365826/93722761-bcb99d00-fb5e-11ea-956b-415570073c4f.png)

I hope it is an easy fix!
Thank you!

**Comment by Velocity23** [comment]
What version are you on?  This should’ve been fixed in the latest update.
