### ISSUE TITLE
Blank Page + Routes

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#176]
**Describe the bug**
I began to add a route to our VANet database and proceeded to finish it in the morning. In the morning, I opened it up and it had the information I had already put in and I finished it, when I clicked add, it took me to a blank page and when I reload it, it is blank. The page I am sent to is http://thai.freecluster.eu/update.php?i=1

**To Reproduce**
1. Begin to add a route to the database
2. Leave your device for a while
3. Complete submitting route
4. Click add route
5. See error

**Expected behavior**
Either route is added or I am redirected to the login page.

**Screenshots**
I don't believe a screenshot is necessary. My entire page is completely white.

**Additional context**
I have never seen this issue before, typically when I come back to finish something, I am redirected to log back in.

**Comment by Velocity23** [comment]
I know the cause of this one, will fix for the next update
