### ISSUE TITLE
Favicon Editing

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#183]
**Is your feature request related to a problem? Please describe.**
Right now, on chrome at least, on most pages there are icons in the left corner of the tab but for Flare it is just an earth, it would be very cool if you could upload a photo to put up there.

**Describe the solution you'd like**
The ability to upload a photo there from the Site Settings.

**Describe alternatives you've considered**
Perhaps there is an alternative but I don't know of it.

**Additional context**
No, I could try to make an example but I am not very good with photo editting.

**Comment by Velocity23** [comment]
This can easily be done on your behalf by just uploading a favicon.ico file to the root directory of your hosting

**Comment by Velocity23** [comment]
@rebal15 You still doing this? If not, I'll get it done and push it as part of Beta 15.

**Comment by rebal15** [comment]
Not needed - you can just upload a favicon to your server.
