### ISSUE TITLE
Slack + Flare Integration

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#184]
**Is your feature request related to a problem? Please describe.**
I don't know if it is possible, but it would be very cool if you could connect a Flare bot to Slack so that you can do / commands in slack such as /hours which could show you how many hours you have or any other things that might work.

**Describe the solution you'd like**
A pilot being able to easily view certain things from Flare directly in Slack.

**Describe alternatives you've considered**
The pilot opening Flare and looking for themselves.

**Additional context**
Once again, this would be cool but it's not a top priority!

**Comment by rebal15** [comment]
@samdog2727 This has been planned, and will be in the works, most likely Version 2.

**Comment by samdog2727** [comment]
@rebal15, that sounds awesome! May I ask:
1. Will this be available with VANet Gold?
2. What integrations do you have planned?

**Comment by Velocity23** [comment]
1.  It'll be separate to VANet
2.  PIREP Notifications and Recruitment Notifications

This will probably end up coming as a plugin (#194) so closing for now.
