### ISSUE TITLE
Inactivity Notice

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#185]
**Is your feature request related to a problem? Please describe.**
Most VAs have a requirement for flights per month. It would be very cool if you could have Flare send an email to the pilot once they reach a threshold of inactivity and you could proceed from there.

**Describe the solution you'd like**
Flare could notify pilots instead of a staff member

**Describe alternatives you've considered**
I don't really know. Maybe a Slack integration could do something like this?

**Additional context**
I understand this might be very difficult as different VAs require different things but it could just be a thought that if easy to do, could help VAs quite a lot.

**Comment by Velocity23** [comment]
Emails are tricky because you need to have certain services set up for them to work properly. This might be something @rebal15 could add in his Patreon fork.
