### ISSUE TITLE
Numbers are Counted Wrong

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#191]
**Describe the bug**
I have noticed that when I input a number, it isn't counted as we usually would count.

**To Reproduce**

Create something that requires a number value and try doing 1, 2, 10. When you see it and use the sort feature to sort from lowest to highest, you should see error.

**Expected behavior**
Numbers should be counted and when sorted from smallest to greatest should actually do so.

**Screenshots**
![Screen Shot 2020-10-04 at 11 44 51 AM](https://user-images.githubusercontent.com/71337097/95020097-0615ec00-0637-11eb-91a0-984e42b9446e.png)

**Additional context**
I have seen this bug while adding gates for events and adding routes to our database.

**Comment by Velocity23** [comment]
We can’t fix this, it’s a bug with the DataTables script which we don’t have control over
