### ISSUE TITLE
Aircraft Comments Field

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#192]
**Is your feature request related to a problem? Please describe.**
My feature is related to a problem. As Thai Group Virtual currently uses AirTable for a crew center, I have been manually adding our routes to the Flare database. As there is no Thai Smiles livery for the A319, I am using Generic and I set required rank to Cadet for the Generic A319. As I am now working on codeshare routes, our required rank for the Air India A319 which uses the Generic livery is Second Officer. My current solution is adding a second A319 Generic but when I go to search for routes from the pilot's perspective, I could easily be confused by 2 A319 Generics and it could lead to them not being able to find the route they want.

**Describe the solution you'd like**
The ability to differentiate ranks from aircraft and having an easy way to differentiate between aircrafts with the same livery. A solution I have thought of is adding the possibility for an "Aircraft Registration" number that is optional but could help you differentiate these.

**Describe alternatives you've considered**
You could just use multiple of the same aircraft but it can get tricky and not very intuitive quite quickly.

**Additional context**
This would be _very_ helpful as it will help pilots (and me) a lot and make routes and aircraft a lot clearer.

**Comment by Velocity23** [comment]
Added notes field in 15

**Comment by Velocity23** [comment]
Should show on pilot side too

**Comment by Velocity23** [comment]
Coming in 17

**Comment by samdog2727** [comment]
@Velocity23 , I don't see this anymore.

**Comment by Velocity23** [comment]
Still there for me, have you got any screenshots?

**Comment by samdog2727** [comment]
Yes, still there. @Velocity23 , sending a screenshot via discord.
