### ISSUE TITLE
Enhanced Pilot Home

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#193]
**Is your feature request related to a problem? Please describe.**
I would find it very helpful if pilots would be able to see upcoming events directly in their pilot home.

**Describe the solution you'd like**
A section displaying the next 1-3 events and if clicked, it would take them to the events page.

**Describe alternatives you've considered**
Notifying pilots via other means of events being posted.

**Additional context**
This isn't a pressing issue but if it is easy, it could be very helpful :)

**Comment by Velocity23** [comment]
Should be easy as, I’ll get this done for you :)

**Comment by Velocity23** [comment]
Fixed in 15
