### ISSUE TITLE
Setup PiReps Issue

### ISSUE THREAD

**Issue by DeclanB2916** [va-net/flare#195]
**Describe the bug**
When I go to file a PiRep in my cc it says I haven’t set PiReps up when I clearly have. I then reset it to find that I have the same issue

**To Reproduce**
1. Go to thai.freecluster.eu
2. Login
3. Scroll down to ACARS
4. Should say “haven’t setup PiReps go to my PiReps”
5. Go to My PiReps
6. Click find me 
7. Should say “successfully found, you can now file PiReps”
8. Go to file PiRep
9. It should say setup PiReps
10. Error replicated

**Expected behavior**
Should be able to file a PiRep easily.

**Comment by Velocity23** [comment]
I can't replicate this locally but I can on your site. I'll look into this.

**Comment by Velocity23** [comment]
Found the issue, fixed in the next one.

**Comment by DeclanB2916** [comment]
Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
