### ISSUE TITLE
More Flexibility In Adding Routes to the Database

### ISSUE THREAD

**Issue by BigBert10** [va-net/flare#197]
**Is your feature request related to a problem? Please describe.**
The VA I work in revolves around a real-world airline. The real-world airline often changes flight numbers and airplanes on their routes. With flight numbers and airplanes that are required to be included in the VA-Net crew center routes database, we will become outdated really quickly in regards to flight numbers and airplanes.

**Describe the solution you'd like**
Including an option to only have the route itself and the duration of the route be a requirement to add to the database. (Ex: DEN-SJC; 2 hours)

**Describe alternatives you've considered**
Tried to add a route without including the flight number or airplane model, but it didn't work.

**Additional context**
N/A

**Comment by Velocity23** [comment]
Flight numbers are an important part of the system and allow pilots to log flights under a certain route and differentiate between similar flights easily. They won't be removed.
