### ISSUE TITLE
Too Many Connections

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#198]
**Describe the bug**
I was inputting a route into our database and I got the error message that is shown in the screenshot.

**To Reproduce**
1. Enter a route
2. See error

**Expected behavior**
Route is added to database successfully.

**Screenshots**
![Screen Shot 2020-10-06 at 8 13 36 AM](https://user-images.githubusercontent.com/71337097/95200117-d76d5200-07ab-11eb-9071-dbaf7113c0ed.png)

**Additional context**
First time I have had this.

**Comment by Velocity23** [comment]
That's a hosting issue, just give it some time and it will resolve itself

**Comment by samdog2727** [comment]
@Velocity23 , I refreshed and it was fine. I just thought I should mention it :)
