### ISSUE TITLE
Pireps not showing in "my Pireps"

### ISSUE THREAD

**Issue by OKCFlight86** [va-net/flare#200]
I filed my first 2 Pireps on the CC. Both Pireps show in the Flight time and the number of flights, but the first flight itself doesn't show in "my pireps"

**To Reproduce**
Unknown atm

**Expected behavior**
I expected both Oak to Las and Las to Rno visible in my filed pireps section

**Screenshots**
N/a

**Debugging Panel**
N/a

**Additional context**
The flight time and hours are correct and it logged both flights in that manner but only shows I flew once.

**Comment by Velocity23** [comment]
Please send a screenshot of your debugging panel

**Comment by OKCFlight86** [comment]
![Uploading B7A82642-FCF0-4E3F-94E8-5DE37BEF05F1.png…]()

**Comment by OKCFlight86** [comment]
![443955EB-F332-40EE-A3AE-9FA4EAFE333F](https://user-images.githubusercontent.com/72451797/95216205-6a5fb980-07b7-11eb-9e1e-384ca774b52d.png)

**Comment by Velocity23** [comment]
Can you update to the latest version then send it again?

**Comment by OKCFlight86** [comment]
![2617DEF4-50E2-4B39-BF49-2912CBA73559](https://user-images.githubusercontent.com/72451797/95548380-8c7d5580-09ca-11eb-9a9a-45c2a3faa288.png)

**Comment by Velocity23** [comment]
I can't reproduce this. Unless you can get some consistent way to get this to happen, it won't be able to be fixed.

**Comment by Velocity23** [comment]
Think I found the root cause of this one... possible fix coming in 1.0.1.

**Please confirm after the update that this is fixed, as I am unable to reproduce this one.**

**Comment by Velocity23** [comment]
Confirmed fixed via Discord
