### ISSUE TITLE
Aircraft Not Showing Up

### ISSUE THREAD

**Issue by BigBert10** [va-net/flare#201]
**Describe the bug**
I tried to add an aircraft (Boeing 737-700/800) without including a livery (since there was no "Southwest" livery), and the aircraft listed as nothing on the fleet list and "()" on the routes list.

**To Reproduce**
1. Go to 'Operations Management'
2. Click on 'Manage Fleet'
3. Add an aircraft without including the livery

**Expected behavior**
I expected the aircraft to be shown as "Boeing 737-700" or "Boeing 737-800" with the required rank needed to fly and the livery field being left blank.

**Screenshots**
<img width="1001" alt="va net issue" src="https://user-images.githubusercontent.com/52386444/95268827-ef18fa80-07ec-11eb-9b60-21e3166c9eba.png">

**Debugging Panel**
N/A

**Additional context**
How do I add a new livery to the livery list? I want a livery that just says "Southwest."

**Comment by Velocity23** [comment]
@BigBert10 The way that list works is all the available liveries in Infinite Flight for that aircraft. Please update to the latest version of Flare (see [here](https://vanet.app/tutorials/flareupdate) for instructions), as the most recent update includes the addition of a notes field for aircraft. The idea then is that if the livery isn't in the livery dropdown you can select the Generic livery and put the airline in the notes. 

Special liveries are difficult to accommodate for, I might add better support for them in the future. For now though, I'll make the livery field required in the next push.
