### ISSUE TITLE
Codeshare Page doesn't Work

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#203]
**Describe the bug**
When I go to the Manage Codeshares page, I get an error.

**To Reproduce**
1. Go to 'Manage Codeshares'
2. Click on 'Manage Codeshares'
3. See error

**Expected behavior**
It opens the manage codeshares page.

**Screenshots**
![Screen Shot 2020-10-07 at 9 20 23 AM](https://user-images.githubusercontent.com/71337097/95336159-5763ec80-087e-11eb-8b7b-7e0d4186237c.png)

**Debugging Panel**
![Screen Shot 2020-10-07 at 9 20 50 AM](https://user-images.githubusercontent.com/71337097/95336204-65b20880-087e-11eb-8e9b-f5b586141ec3.png)

**Additional context**
This happens everytime I attempt to open this page but all other pages work.

**Comment by Velocity23** [comment]
Fixed in 17
