### ISSUE TITLE
Add Aircraft Livery Loading Bug

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#204]
**Describe the bug**
When I went to add an aircraft to our fleet, I clicked on 777-300ER and then I went to livery and it just says loading and never shows a livery. I waited 5 minutes and then I refreshed the page and tried again. I also attempted with other aircraft and the same thing happens.

**To Reproduce**
1. Go to 'Manage Fleet'
2. Click on 'Add Aircraft'
3. Click on 'Boeing 777-300ER'
4. Click on 'Livery'

**Expected behavior**
A list of liveries is displayed for me to choose from.

**Screenshots**
![Screen Shot 2020-10-09 at 9 00 57 AM](https://user-images.githubusercontent.com/71337097/95585951-f539f180-0a0d-11eb-91ae-95a736b91fd1.png)

**Debugging Panel**
![Screen Shot 2020-10-09 at 9 01 27 AM](https://user-images.githubusercontent.com/71337097/95586000-0551d100-0a0e-11eb-950e-9e7881891e88.png)

**Additional context**
I haven't had this issue in the past.

**Comment by Velocity23** [comment]
Fixed in 17
