### ISSUE TITLE
Codeshare Issue

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#206]
**Describe the bug**
Upon submitting a codeshare request, I receive a completely white screen.

**To Reproduce**
Submit a codeshare request and see error

**Expected behavior**
Perhaps a successful Codeshare request confirmation box.

**Screenshots**
Self-explanatory

**Debugging Panel**
![Screen Shot 2020-10-14 at 2 30 53 PM](https://user-images.githubusercontent.com/71337097/96030324-ded6d000-0e29-11eb-950c-b2b3bece2635.png)

**Additional context**
I have never made a codeshare request before.

**Comment by Velocity23** [comment]
Known issue, fixed in the next one. Was meant to be fixed in 17 but I forgot to include the file in the updater.
