### ISSUE TITLE
Incorrect Header Links

### ISSUE THREAD

**Issue by Bears-Beets-BSG** [va-net/flare#208]
**Describe the bug**
Clicking on "Pilot Panel" and "Log Out" in the header results in a 404 error.

**To Reproduce**
1. Click on 'Pilot Panel' or 'Log Out'
2. See 404 error page

**Expected behavior**
Going to the Home Page or logging out (being taken to the login page).

**Screenshots**
<img width="794" alt="Screen Shot 2020-10-14 at 2 57 57 PM" src="https://user-images.githubusercontent.com/50090529/96033835-a08fdf80-0e2e-11eb-86dc-2d533c3b8c5a.png">
<img width="829" alt="Screen Shot 2020-10-14 at 2 57 22 PM" src="https://user-images.githubusercontent.com/50090529/96033840-a1287600-0e2e-11eb-8d06-8c5b745ac301.png">

**Debugging Panel**
<img width="866" alt="Screen Shot 2020-10-14 at 2 51 55 PM" src="https://user-images.githubusercontent.com/50090529/96033870-ad143800-0e2e-11eb-98a2-c336f50e60d3.png">

**Additional context**
It seems links were not updated to being outside of the /admin/ folder.

**Comment by Velocity23** [comment]
Fixed in the next one
