### ISSUE TITLE
Codeshare Request Options For Flight Numbers

### ISSUE THREAD

**Issue by Bears-Beets-BSG** [va-net/flare#209]
**Is your feature request related to a problem? Please describe.**
Sort of. When you receive a codeshare request, those routes are added with the other VA's callsign prepended (e.g., BAVABA123 instead of just BA123). This could be useful for VOs that would like to see the codeshare partner's callsign in front of the flight number, but for VAs simulating real-world features, forcing this could be an issue.

**Describe the solution you'd like**
An option could be added when importing codeshare to ask the user whether or not they would like to prepend the codeshare partner VA's callsign to the flight numbers about to be imported.

For example:
- IFVA uses IF123 for flight numbers, JAVA (Just Another VA) uses JA123 for flight numbers.
1. Codeshare request is received by IFVA.
2. Import button is clicked by IFVA Routes Manager.
3. Instead of all JA flight numbers being added as "JAVAJA123" (current default), IFVA Routes Manager gets asked: "Please choose the format you would like to import the codeshare flight numbers with: (1) JAVAJA123, (2) JAVA123, (3) JA123, (4) IFJA123, (5) CSJA123."

**Describe alternatives you've considered**
None.

**Additional context**
Nope.

**Comment by Velocity23** [comment]
Fixed in next one. Couldn't give a whole lot of options, so I'm just trimming the letters (if any) from the start of the flight number before adding the VA's code. I know it's not ideal, but giving options and keeping a good UI is hard.
