### ISSUE TITLE
Banner Announcement

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#222]
**Is your feature request related to a problem? Please describe.**
Not really. I just see in the future that some pilots might not see/check the _News Feed_ section. 

**Describe the solution you'd like**
Perhaps you could have the option to send a short message that shows up as a banner at the top of the Pilot Panel that can go away when the (x) is clicked on. This banner will show up for either 3, 5 or 7 days based on what the administrator decides.

**Describe alternatives you've considered**
Using the news feed.

**Additional context**
This is just an idea. Low priority.

**Comment by Velocity23** [comment]
Not sure if this is really practical, might be a bit cluttered. Maybe a plugin thing?

**Comment by Velocity23** [comment]
Not practical for now
