### ISSUE TITLE
Plugin Store Description

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#223]
**Is your feature request related to a problem? Please describe.**
Yes. When I went to the plugin store, I saw a new plugin called "Activity". I did not fully understand what it was so I was forced to download it.

**Describe the solution you'd like**
When you click on the name of the plugin in the plugin store, it shows a small paragraph or 2 describing what the plugin is.

**Describe alternatives you've considered**
Downloading the plugin and seeing for yourself.

**Additional context**
This would be helpful if it is easy to add.

**Comment by Velocity23** [comment]
Fixed in 19
