### ISSUE TITLE
Wording for Codeshare Section

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#224]
**Is your feature request related to a problem? Please describe.**
Yes, the wording on the codeshare section can be confused with receiving routes instead of giving the other VA routes.

**Describe the solution you'd like**
The wording to be more clear on that area.

**Describe alternatives you've considered**
I don't think there really is an alternative.

**Additional context**
Jon and I tried this and experienced this issue first hand.

**Comment by Velocity23** [comment]
Fixed in 19
