### ISSUE TITLE
Estimated Flight Time

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#227]
**Is your feature request related to a problem? Please describe.**
While searching the route database for a route to fly, I wanted to know how long the flight time was supposed to be but I had to look it up.

**Describe the solution you'd like**
The flight time field is shown when searching for a route in the route database.

**Describe alternatives you've considered**
If you click on the flight time, a thing opens up showing the information like how it looks when you input a route into the Manage Routes screen but the only difference would be that you could not edit it.

**Additional context**
This should be easy to do and would be very helpful.

**Comment by Velocity23** [comment]
Fixed in 19
