### ISSUE TITLE
Added Links

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#228]
**Is your feature request related to a problem? Please describe.**
This issue is not related to a problem I have had.

**Describe the solution you'd like**
The screenshot I have attached will really help explain my point. On the top left of Flare, you see a link to "Pilot Panel" and "Log Out". It would be cool if you could call these "Link 1", "Link 2", and add a "Link 3". In the vanilla version of flare (for lack of a better word), it would be displayed like this, but in Settings, it would be cool if you could configure it to direct someone to your website, or another thing like this. 

**Describe alternatives you've considered**
This is optional but seems easy to do so I don't think an alternative is really necessary.

**Additional context**
![Screen Shot 2020-10-24 at 2 05 52 PM](https://user-images.githubusercontent.com/71337097/97088922-24ea1b80-1602-11eb-8a9a-5f0b7570e50e.png)

**Comment by Velocity23** [comment]
I like it. I'll make some changes in 19 that make this possible for plugins, then transfer this issue to the plugins repo so it can be done as a plugin.

**Comment by Velocity23** [comment]
Added in 19, will open a separate issue in the Plugins repo for you.
