### ISSUE TITLE
Notes Do Not Show in Route Databsae

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#236]
**Describe the bug**
The notes on aircraft don't show when searching by aircraft in the routes database or when viewing flights.

**To Reproduce**
Add notes to aircraft and search for aircraft in Route Database.

**Expected behavior**
The notes to show during both of the events.

**Screenshots**
I think my point describes itself.

**Debugging Panel**
![Screen Shot 2020-10-26 at 9 03 40 AM](https://user-images.githubusercontent.com/71337097/97175610-26365800-176a-11eb-8ccb-f0b627d07bbb.png)

**Additional context**
This problem was an issue earlier as well.

**Comment by Velocity23** [comment]
Added in 21
