### ISSUE TITLE
Search By Flight Time Error

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#237]
**Describe the bug**
When you search for routes that are <1 hour, you get other routes as well.

**To Reproduce**
1. Go to 'Route Database'
2. Click on 'Flight Time'
3. Scroll down to '<1 hour'
4. Search for routes
5. See Error

**Expected behavior**
Routes under 1 hour will appear.

**Screenshots**
![Screen Shot 2020-10-26 at 9 08 14 AM](https://user-images.githubusercontent.com/71337097/97176062-c9876d00-176a-11eb-9c35-eb6cd77f75a6.png)

**Debugging Panel**
![Screen Shot 2020-10-26 at 9 08 53 AM](https://user-images.githubusercontent.com/71337097/97176125-e02dc400-176a-11eb-807f-ac00f79e027e.png)

**Additional context**
This is a strange issue that I have seen for a while but I have forgotten to report. All of the other Flight Time searches work correctly expect for this one.

Also, I am sent to this link: http://thai.freecluster.eu/routes.php?action=search&dep=&arr=&fltnum=&aircraft=&duration=0
I don't know if that is normal, but I thought maybe duration=0 has something to do with it.

**Comment by Velocity23** [comment]
Fixed in 21, thanks for the report.
