### ISSUE TITLE
View Codeshare IDs

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#238]
**Is your feature request related to a problem? Please describe.**
If I want to request a codeshare, I am not able to see what the other VA's codeshare ID is. 

**Describe the solution you'd like**
A table (or something else) in the Manage Codeshare area that tells you what each VA's codeshare ID is.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Velocity23** [comment]
The idea is that you can only share routes with people who given you their ID. You can find your ID in your VANet Profile.
