### ISSUE TITLE
Route Database Connection to Routes

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#244]
**Describe the bug**
I was going through my aircraft and I noticed that one looked strange, so I looked up routes in my database using the Thai A380 and it showed nothing. Then I looked at the routes in "Manage Routes" and I saw several A380 routes including VTBS-EGLL. I then looked at VTBS - EGLL in the Routes Database and no flights showed up!

**To Reproduce**
Not sure how to reproduce this. @Velocity23 can see our crew center so you can look there.

**Expected behavior**
The routes to be connected between Manage Routes and the database.

**Screenshots**
N/A

**Debugging Panel**
![Screen Shot 2020-10-30 at 8 53 45 AM](https://user-images.githubusercontent.com/71337097/97707268-6c9ef600-1a8d-11eb-833b-29319b7eb278.png)

**Additional context**
This is very strange.

**Comment by Velocity23** [comment]
Fixed in 22
