### ISSUE TITLE
Blank Screen When Accepting PIREP

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#250]
**Describe the bug**
When I clicked the green checkmark on the line of a pilot's flight that they logged, I was shown a blank page.

**To Reproduce**
Validate a flight and you should see the error.

**Expected behavior**
You should be sent back to the "Pending PIREPs" page

**Screenshots**
N/A - self explanatory

**Debugging Panel**
![Screen Shot 2020-11-09 at 3 51 16 PM](https://user-images.githubusercontent.com/71337097/98594996-684fb580-22a3-11eb-9000-329c8711c94c.png)

**Additional context**
I've had this issue before in a different place I believe.

**Comment by Velocity23** [comment]
Can't reproduce this on 1.0.1. I'll push an update to the file in the next update though just in case there's a discrepancy.

**Comment by Velocity23** [comment]
Leaving open for now, let me know if it's fixed after the next update.

**Comment by Velocity23** [comment]
@samdog2727 Any luck?

**Comment by samdog2727** [comment]
I haven't had this issue anytime recently.

**Comment by Velocity23** [comment]
Sweet!
