### ISSUE TITLE
Flight Time Discrepancy

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#252]
**Describe the bug**
If you already have a value listed for a pilot's flight time, if you want to go add more hours in "Manage Users", their flight time shows a different (much larger) number. This number is different with different pilots and only sometimes happens (60% or the time).

**To Reproduce**
1. Go to 'Manage Users'
2. Click on a pilot with hours already
3. See difference in hours between their hours and what is shown.

**Expected behavior**
The hours to match

**Screenshots**
![Screen Shot 2020-11-10 at 8 57 57 AM](https://user-images.githubusercontent.com/71337097/98683269-d55e5c00-2332-11eb-90ac-382c98d36698.png)

![Screen Shot 2020-11-10 at 8 58 15 AM](https://user-images.githubusercontent.com/71337097/98683360-ef983a00-2332-11eb-99c4-34905c105762.png)

**Debugging Panel**
![Screen Shot 2020-11-10 at 8 59 00 AM](https://user-images.githubusercontent.com/71337097/98683391-faeb6580-2332-11eb-84d5-462dc81d52a5.png)

**Additional context**
N/A

**Comment by Velocity23** [comment]
I did a stupid :man\_facepalming: 

Fixed in the 1.1.0 beta.
