### ISSUE TITLE
Livery type at "Loading" when importing routes with phpVMS importer

### ISSUE THREAD

**Issue by nicholastanjj** [va-net/flare#254]
When importing a route with phpVMS's CSV format, after selecting a aircraft, the livery is stuck at "loading" and no livery shows up.

<img width="1440" alt="Screenshot 2020-11-15 at 5 59 06 PM" src="https://user-images.githubusercontent.com/68290711/99181983-e6f99680-276c-11eb-93c4-2696159ccd5b.png">

**Comment by Velocity23** [comment]
Fixed in 1.1
