### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by nicholastanjj** [va-net/flare#255]
When trying to install any plugin, this error pops up. However, the plugin doesn't seem to have been installed as it is not in the "installed" section, neither is there any additional features available related to the plugin.

<img width="1440" alt="Screenshot 2020-11-15 at 6 12 05 PM" src="https://user-images.githubusercontent.com/68290711/99182162-368c9200-276e-11eb-9814-66d25bfad17a.png">

**Comment by Velocity23** [comment]
In future, please use the template.

Have you had this plugin installed in the past?

**Comment by Velocity23** [comment]
@nicholastanjj I really need more information on this please

**Comment by nicholastanjj** [comment]
I did install it, but nothing showed up, which is why I tried installing it again but to no avail.

**Comment by Velocity23** [comment]
Should be fixed in 1.0.2
