### ISSUE TITLE
Aircraft Not Shown when Filing PIREP

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#266]
**Describe the bug**
When filing a PIREP, no aircraft are available to choose from.

**To Reproduce**
1. Go to 'File PIREP'
2. Click on 'Aircraft'
3. See error

**Expected behavior**
A list of aircraft available at the pilot's rank to show up.

**Screenshots**
![Screen Shot 2020-11-30 at 8 18 09 AM](https://user-images.githubusercontent.com/71337097/100614740-980f3d80-32e4-11eb-96c0-65f1ac4bd282.png)

**Debugging Panel**
![Screen Shot 2020-11-30 at 8 18 32 AM](https://user-images.githubusercontent.com/71337097/100614767-a3faff80-32e4-11eb-8a26-e9ad3ed6c7fa.png)

**Additional context**
All of my pilots are having this bug.

**Comment by Velocity23** [comment]
Fixed in the next one, thanks
