### ISSUE TITLE
Flight time and transfer time not in synced 

### ISSUE THREAD

**Issue by OKCFlight86** [va-net/flare#268]
**Describe the bug**
I enter the transfer flight time which is still duplicating but it isn’t corresponding with the flight time listed under manage users. I have a pilot (southwest 08VA for picture purpose) with 20 transfer hours and 18 current flight hours on this CC but only showing 18 under flight time.

**To Reproduce**
Unsure at the moment. 

**Expected behavior**
Expected the 20 transfer hours and the 18 flown on this crew center to show 38 under flight time.

**Screenshots**
![0D2D9650-5470-4306-AB44-5AB68C0CC0BD](https://user-images.githubusercontent.com/72451797/101368793-2ea3a780-386d-11eb-89c6-0ef8b53c68da.jpeg)
![562F9723-ECC3-4220-9DCF-5F2C82F6B328](https://user-images.githubusercontent.com/72451797/101368811-32372e80-386d-11eb-9d73-4a6928917c1b.jpeg)

**Debugging Panel**
N/A

**Additional context**
Flare 1.0.2

**Comment by Velocity23** [comment]
This should've been fixed a while back - I can't reproduce it now. I'll try pushing the file as part of the next update
