### ISSUE TITLE
Deleting inactive pilots/duplicate pilots

### ISSUE THREAD

**Issue by OKCFlight86** [va-net/flare#269]
**Is your feature request related to a problem?
- No. but the find me feature for some pilots have made it impossible to file a flight plan which is making them to have to create a second profile leaving one a complete waste of a call sign since that profile has to have one.  

**Describe the solution you'd like**
Instead of having just a view info option and a inactive option (that looks like a delete option) for pilots, please make an actual deletion option of pilots/user.
**Describe alternatives you've considered**
When a pilot cannot find himself after numerous hours of trying to walk them through it, they have to create a new account. At that time I have to inactive their old account and assign a random call sign. I also have to change their email address etc. that’s too much when a delete option is immediate

**Additional context**
Thanks for your work.

**Comment by zhf21** [comment]
I would love this! 

_Am I allowed to comment?_

**Comment by zhf21** [comment]
Hello. Just checking in. At the moment, is this feasible? It would be great to have. Old accounts are causing clutter and causing issues with duplicate callsigns and such in the event that a pilot needs to create a new account.

**Comment by velocity23** [comment]
@zhf21 The issue logistically is that pilots are associated with heaps of stuff like PIREPs, Permissions, and more. If you delete a pilot completely, you mess up all of that. At that stage there are two options:
1. Also removed everything associated with that pilot (ie also delete all of their PIREPs)
2. Rewrite some of the logic in how these things are displayed to account for the fact that a pilot associated with a PIREP for example might not actually exist.

**Comment by OKCFlight86** [comment]
Seems pretty simple that you’d just delete all of their pireps etc also... if they are not using that callsign, shouldn’t matter. Delete is to delete. We should also have an inactive option. I never wanted that to change I wanted an additional option to delete user and all that’s with it.
