### ISSUE TITLE
Ranking up notifies staff/pilot 

### ISSUE THREAD

**Issue by OKCFlight86** [va-net/flare#272]
**Is your feature request related to a problem? Please describe.**
-Not related to any issue unless you consider transfer hours and crew center hours not matching. 

Be nice for pilots and staff to be alerted when a new rank is met. That would be based on the rankings we input in operations. (Of course transfer hours and CC hours need to be right first)

**Describe the solution you'd like**
When a pilot files a pirep and it’s approved and the hours go to a new rank, the pilot and staff should be alerted to the change of ranks. This will allow staff to keep badges updated without having to manually check where everyone is and who will need new badges/status card updates. Also avoids pilots having to reach out. Overall would be smoother

**Describe alternatives you've considered**
Manually looking at hours and cross checking our list for pilots and their current ranks

**Additional context**
None

**Comment by Velocity23** [comment]
Would this be part of the notifications system or the Slack/Discord Plugin?

**Comment by OKCFlight86** [comment]
Are you asking me? Idk bout the slack/discord plug-in... But I figured it would be a notification to pilot and staff etc

**Comment by Velocity23** [comment]
Coming in the next one
