### ISSUE TITLE
Error 404, Route Database

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#277]
**Describe the bug**
When looking at routes, I pressed the + button next to the airplane button and I get taken to an Error 404 page.

**To Reproduce**
1. Go to 'Routes Database'
2. Search for any route
3. Click the '+' button

**Expected behavior**
Honestly not sure what is supposed to happen here.

**Screenshots**
![Screen Shot 2020-12-15 at 8 38 34 AM](https://user-images.githubusercontent.com/71337097/102222066-ee69a800-3eb0-11eb-9908-7679b00be191.png)

**Debugging Panel**
![Screen Shot 2020-12-15 at 8 39 00 AM](https://user-images.githubusercontent.com/71337097/102222105-fcb7c400-3eb0-11eb-8fca-bae9a354d7e8.png)

**Additional context**
I am on Beta 4.

**Comment by Velocity23** [comment]
@samdog2727 If you hover over the plus button, then right click (or Cmd Click on Mac), then click Copy Link Location (or similar), what does it say?

**Comment by Velocity23** [comment]
Never mind, found the issue, fixed for the next push
