### ISSUE TITLE
Error Updating Routes

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#278]
**Describe the bug**
After updating to Beta 4 for Flare 1.10, when I go to Manage Routes, certain routes do not have any aircraft anymore and when I edit the route to include the correct aircraft, it says Error Updating Route.

**To Reproduce**
1. Go to 'Manage Routes'
2. Click on any route and edit it 
3. Add an aircraft

**Expected behavior**
The route to update correctly

**Screenshots**
![Screen Shot 2020-12-16 at 8 32 59 AM](https://user-images.githubusercontent.com/71337097/102355253-9c408980-3f79-11eb-8d78-3011794640a0.png)

**Debugging Panel**
![Screen Shot 2020-12-16 at 8 35 32 AM](https://user-images.githubusercontent.com/71337097/102355294-ab273c00-3f79-11eb-9363-5f519849ea95.png)

**Additional context**
I had this issue yesterday as well.

**Comment by Velocity23** [comment]
@samdog2727 I'm gonna need access to your DB for this one, I'll message you on discord

**Comment by Velocity23** [comment]
Oh wait, I know what this one is. Was fixed in the most recent push.
