### ISSUE TITLE
Unable to access freecluster 

### ISSUE THREAD

**Issue by Loogie125** [va-net/flare#279]
**Describe the bug**
Safari cannot open the page because the server cannot be found
Apple iPad Pro gen 4 12.9 inch,  iOS 14.2, on safari. Attempted on google chrome as well, same result.
No VPN used, location Thailand.

http://thai.freecluser.eu/

**To Reproduce**
1. Teammate asked to click http://thai.freecluser.eu/
2. Copied link and pasted in safari (and later google chrome)
3. See error

**Expected behavior**
I would’ve expected a webpage....

**Screenshots**
Please send me an email if you wish to see screenshots, I am unable to paste them here.

**Debugging Panel**
If you are on a Prerelease version of Flare, you will have a debugging panel available under *Site Settings*. Attach a screenshot of that screen here.

**Additional context**

**Comment by Velocity23** [comment]
Host issue, not our problem

**Comment by Loogie125** [comment]
Cheers. My boss told me to message you but thanks.

**Comment by samdog2727** [comment]
Thanks @Velocity23 lol
