### ISSUE TITLE
PIREP goes Crazy

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#281]
**Describe the bug**
One of my pilots filed the PIREP: NZAA - KLAX and it was filed 7 times.
**To Reproduce**
1. File a PIREP
2. See error

**Expected behavior**
The PIREP is filed once

**Screenshots**
![Screen Shot 2020-12-18 at 9 22 39 AM](https://user-images.githubusercontent.com/71337097/102624836-94681d00-4112-11eb-839b-d610b90e2a58.png)

**Debugging Panel**
![Screen Shot 2020-12-18 at 9 23 03 AM](https://user-images.githubusercontent.com/71337097/102624877-a2b63900-4112-11eb-9467-e7920610ba52.png)

**Additional context**
Freaked out the pilot 😂 . I haven't had any other PIREPs so I can't tell you if it's isolated to this one pilot or not. I will update this thread when new information becomes available.

**Comment by Velocity23** [comment]
Seems like user error to me, I can reproduce it. Let me know if you get some consistent reproduce steps.
