### ISSUE TITLE
Unable to edit Approved PIREPs

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#282]
**Describe the bug**
This is just another of the same type of bug. When I went to edit a PIREP that I had already approved, if it was in the 1st page, then I could edit it fine but if it was in a later page I could not.

**To Reproduce**
1. Go to 'Manage PIREPs'
2. Click on 'All PIREPs'
3. Go to Page 2 or later
4. Click the 'Actions' button on any of those PIREPs
5. See Error

**Expected behavior**
The ability to edit the PIREPs as I can do with page 1

**Screenshots**
N/A

**Debugging Panel**
![Screen Shot 2020-12-18 at 9 26 41 AM](https://user-images.githubusercontent.com/71337097/102625218-253ef880-4113-11eb-9043-6dec2bbaa98f.png)

**Additional context**
This has happened in other places as well. I believe you need to increase the rate of something to fix it.

**Comment by Velocity23** [comment]
Fixed in the next one, thanks
