### ISSUE TITLE
Route Search not working?

### ISSUE THREAD

**Issue by CaptainGeorgeIF** [va-net/flare#285]
**Describe the bug**
Whenever I try to search a route, no matter what I try to put in, it will always say "No data available in table".

**To Reproduce**
1. Go to 'Route Database'
2. Fill in the information from an existing route
3. See error

**Expected behavior**
Give me an existing route

**Debugging Panel**
![image](https://user-images.githubusercontent.com/50553084/103097033-38b3fd00-4606-11eb-93c1-4838f1d40d3c.png)

**Comment by samdog2727** [comment]
@CaptainGeorgeIF , what rank are you in your crew center? Are you at a high enough rank to fly the route you are searching for? Another suggestion, make sure that all the fields match up correctly. Check that the variables you requested correlate with those of the route you are flying.

**Comment by CaptainGeorgeIF** [comment]
We currently only have one rank which is gained when having 0 flight hours.

**Comment by Velocity23** [comment]
No issues for me, I expect the details you're entering are slightly incorrect. What is the route info/search parameters
