### ISSUE TITLE
Airline ICAO Code Doesn't Display When Filing a PIREP Through ACARS

### ISSUE THREAD

**Issue by zhf21** [va-net/flare#286]
**Describe the bug**
When I use ACARS and put in a flight number, I don't have the option to add the airline ICAO code, just the number.

**To Reproduce**
1. Go to 'ACARS'
2. Click on 'Run ACARS'
3. Attempt to add the airline ICAO code
4. Doesn't display

**Expected behavior**
The airline ICAO code shows up.

**Screenshots**
N/A

**Debugging Panel**
N/A

**Additional context**
It would be greatly appreciated if this could be fixed ASAP!

**Comment by Velocity23** [comment]
This was fixed in v1.1.0

**Comment by zhf21** [comment]
Ah, okay. Sorry about that!
