### ISSUE TITLE
Error Updating/Adding Routes

### ISSUE THREAD

**Issue by zhf21** [va-net/flare#287]
**Describe the bug**
When I attempt to update/add a route, I receive an error.

**To Reproduce**
1. Go to 'Operations Management'
2. Click on 'Manage Routes'
3. Scroll down to 'Add Route' or the edit button
4. Add/update the route
5. See error

**Expected behavior**
The route is added/updated

**Screenshots**
<img width="1438" alt="Screen Shot 2020-12-26 at 5 32 31 PM" src="https://user-images.githubusercontent.com/67797012/103160238-587f2880-47a0-11eb-8ad2-b420019d8fac.png">

**Debugging Panel**
N/A

**Additional context**
N/A

**Comment by zhf21** [comment]
Appears the Sam had the same issue. I do recall this being fixed back in Beta 5, but since Beta 6 the issue has returned.

https://github.com/va-net/flare/issues/278#issue-768875594

**Comment by velocity23** [comment]
Got it, hotfix coming soon
