### ISSUE TITLE
Ability to Reactivate a Deactivated User

### ISSUE THREAD

**Issue by zhf21** [va-net/flare#288]
**Is your feature request related to a problem? Please describe.**
Unless you are supposed to be able to change a pilots' status, then no, I don't believe so.

**Describe the solution you'd like**
I'd like to be able to reactivate a deactivated pilot.

**Describe alternatives you've considered**
Creating a new account (inefficient).

**Additional context**
N/A

**Comment by velocity23** [comment]
Coming in the next push
