### ISSUE TITLE
Duplicate PIREPs in Discord

### ISSUE THREAD

**Issue by zhf21** [va-net/flare#290]
**Describe the bug**
When receiving a notification saying that a PIREP has been filed, it appears twice.

**To Reproduce**
1. Setup a PIREP integration with Discord
2. File a PIREP
3. Check Discord
4. See duplicate PIREP

**Expected behavior**
Single PIREP shows up

**Screenshots**
<img width="538" alt="Screen Shot 2020-12-26 at 8 33 53 PM" src="https://user-images.githubusercontent.com/67797012/103162236-254a9280-47bc-11eb-8b3f-4be510c895c3.png">

**Debugging Panel**
N/A

**Additional context**
N/A

**Comment by velocity23** [comment]
Looks like an issue on your end, I can't reproduce this. Try reconfiguring your webhooks.
