### ISSUE TITLE
Error Filing PIREP with ACARS

### ISSUE THREAD

**Issue by zhf21** [va-net/flare#292]
**Describe the bug**
When filing a PIREP using ACARS, an error message appears.

**To Reproduce**
1. Go to 'ACARS'
2. Click on 'Select Server'
3. Click on 'Expert Server'
4. Fill in the appropriate information
5. Submit PIREP
5. See error

**Expected behavior**
PIREP is filed.

**Screenshots**
<img width="1087" alt="Screen Shot 2020-12-28 at 1 42 38 PM" src="https://user-images.githubusercontent.com/67797012/103236516-19bdaf80-4913-11eb-9505-ce8bc7b47ca0.png">

**Debugging Panel**

**Additional context**
It tells me I'm not of rank; however, I have over 800 hours, which well meets the requirements to fly the 787-10. I have checked to make sure that the plane is set for the appropriate rank. Additionally, when filing a PIREP manually, there is no issue.

**Comment by velocity23** [comment]
Should be fixed for the next release
