### ISSUE TITLE
Option to integrate SimBrief or FPLtoIF.com

### ISSUE THREAD

**Issue by CaptainZac1** [va-net/flare#294]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the page that shows flight information, there will be SimBrief.com or FPLtoIF.com below it, so a flight plan automatically pops up to make flying a breeze for pilots

**Describe alternatives you've considered**
You can find a way to integrate Google maps API so a route shows up on the screen. It may not have sectors, but it shows the two airports and a line between them so it shows the route.

*Additional Notes*
now I know this isn’t a problem related directly to the crew center, but I think would be a nice option to have for pilots to make flying just a little bit easier for them. Some pilots say that they don’t want to fly because flight plan takes too long etc... so I think this would be a great way to boost pilot activity and VAs that want to use VAnet. But I do want to make sure the issue of the flights not showing up is resolved first.

**Comment by velocity23** [comment]
I've talked to Chris about this before, there's no great way to integrate FPLtoIF at the moment and Simbrief is too complicated. I know this is wanted though, so I'm gonna close this for now and will definitely implement it in the future if it becomes possible.
