### ISSUE TITLE
Flare Version 1.2.0 Roadmap

### ISSUE THREAD

**Issue by velocity23** [va-net/flare#295]
# Summary

Flare v1.2.0 focuses on two main things - speed and development. We're introducing some new features to help speed up the loading of Flare, and also implementing some new tech to help speed up development and patches in the future.

# Legend

Items in each section include the following icons:
📄 In Planning
👨‍💻 In Progress
✅ Completed

# Feature List

| Status | Feature | Assignee |
| -- | -- | -- |
| ✅ | Automatic Callsign Assignment [#253] | @velocity23 |
| 👨‍💻 | Programmatic Forms | @velocity23 |
| ✅ | More Frontend Loading | @velocity23 |
| ✅ | Analytics & Error Reporting | @velocity23 |
| ✅ | Caching | @velocity23 |
| ✅ | Ability to Reactivate Deactivated Users [#288] | @velocity23 |
| ✅ | Route Deletion Confirmation [#284] | @velocity23  |

# Feature Overviews

## Automatic Callsign Assignment

This feature will add the ability for callsigns to be determined automatically with no user choice. This feature will be able to be disabled.

## Programmatic Forms

A new `Form` class that means that forms can be created and rendered programmatically. An instance of this class will have methods to add fields and customize the form overall, as well as a `render()` method to show the form.

## More Frontend Loading

With the introduction of the Flare API in v1.1.0, more data can be grabbed client-side for things such as modals and non-default tabs.

## Analytics & Error Reporting

VAs may opt-into sending analytics and error reports to a central Flare server. This information will be visible in an internal dashboard.

## Caching

Currently, VANet is pinged with a MyInfo request every time a page is loaded. If we cache the response if the database then loading times will be improved. This also opens up opportunities for other caching.

## Ability to Reactivate Deactivated Users
See #288 

## Route Deletion Confirmation
See #284

**Comment by CaptainZac1** [comment]
Hey, just a quick question for you all. Will the route database error be fixed in 1.2.0?

**Comment by velocity23** [comment]
> Hey, just a quick question for you all. Will the route database error be fixed in 1.2.0?

Was fixed in 1.1.1 😉

**Comment by velocity23** [comment]
**Flare v1.2.0 is on short final! Look out for a release announcement on discord and the IFC!**
