### ISSUE TITLE
Callsigns Being Reserved for Rejected Pilots

### ISSUE THREAD

**Issue by CPTWilliamSE** [va-net/flare#299]
**Describe the bug**
Pilots that apply automatically reserve a callsign. This reservation is still active even after being rejected. The callsign the rejected applicant reserved is still reserved. The only way to free up the callsign again is to delete the applicant or the applicants callsign directly from the SQL database.

**To Reproduce**
1. Create a new application, remember the callsign.
2. Log onto an admin account and reject the application and log out.
3. Now create another application with the same callsign as before.

**Expected behavior**
The expected behaviour would be for the system to delete the callsign from the database so that new applicants may use it.

**Comment by velocity23** [comment]
Known

**Comment by samdog2727** [comment]
Will this be fixed at some point soon @velocity23 ?

**Comment by velocity23** [comment]
It's hard to say. There's actually something in the database that's preventing us from having duplicate callsigns, and of course we can remove it but it is good for speed. We'll talk about it internally.
