### ISSUE TITLE
Site Management Issue

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#301]
**Describe the bug**
It's not really a bug, to be honest. When you open "Manage PIREPs", the Site Management dropdown menu expands. I'm assuming the "PIREP Management" dropdown should expand instead.

**To Reproduce**
1. Go to 'PIREP Management'
2. Click on 'Manage PIREPs'
3. See error

**Expected behavior**
I assume that the PIREP Management dropdown would open instead.

**Screenshots**
N/A

**Flare Version**
v1.2.0-beta1 but it was happening on the most recent version before this beta.

**Additional context**
N/A

**Comment by velocity23** [comment]
Fixed for the next push, thanks for that
