### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#302]
**Describe the bug**
I clicked on 'Manage Users' and it worked, then it went to Manage PIREPs and then back to Manage Users. The Manage Users page was slow so I clicked it again and I got "SQLSTATE[HY000] [2002] Connection refused".

**To Reproduce**
See above. I'm not sure it is possible to reproduce.

**Expected behavior**
Manage Users page to open.

**Screenshots**
N/A

**Flare Version**
V1.2.0-Beta1

**Additional context**
Just updated to Beta

**Comment by velocity23** [comment]
Host issue, just give it some time
