### ISSUE TITLE
Add Flight Time Multi Code

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#303]

**Comment by CPTWilliamSE** [comment]
Have you considered running a stable version of flare for your pilots and having a subdomain for the beta testing? That's how our crew center is setup. We actually got a few test sites which we are able to "play" on.

Removing the transfer hours feature completely is definitely not something i'd like as then there would be no way to remove hours from the pilots. Say for example you accidentally hit the 0 too many times XD.

**Comment by samdog2727** [comment]
Those are good points you make.
1. I'll keep in mind creating a new site for Beta only.
2. If you remove the Transfer Hours feature, I would hope you could subtract hours by entering negative values.

**Comment by velocity23** [comment]
I don't think removing the transfer hours section really works, but may I ask what's wrong with just adding the time to the transfer hours section? I know it's not the most convenient but it seems like a bit of a far-fetched use case. 

For the time bonuses thing, maybe that could be something implemented with multiplier codes. Perhaps you could have the option of giving a multiplier or an hours addition. For instance, you could give pilots who use that code 5 extra hours, or you could give them 2x flight time. Does that make sense?
