### ISSUE TITLE
Site Dashboard Issues

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#305]
**Describe the bug**
There are several issues but I am putting them together as they are pretty related.
1. "PIREPs Over Time" - This issue is that the graph is not easy to interact with. Each "Time" datapoint is evenly spread out even though sometimes if there are no filed PIREPs it skips a day and the measure doesn't become uniform.
2. "Applications Over Time" - Same issue as PIREPs Over Time
3. "Pilot Leaderboard" - This does not show the past 7 days, it either shows 90 or total, I can't tell which.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Flare Version**
V.1.2.0-beta1
**Additional context**
N/A

**Comment by CPTWilliamSE** [comment]
I would like to add to this topic as I did some digging into our dashboard page and found an additional issues.

The dates on both graphs arent always ordered by date. For example it goes 12-23 12-24 then somehow to 12-22 and then back to 12-25.

![Screenshot_2021-01-13 Site Dashboard - Suisse Virtual](https://user-images.githubusercontent.com/76994465/104429382-d6577800-5585-11eb-92b0-5cdbcf873ad1.png)
![Screenshot_2021-01-13 Site Dashboard - Suisse Virtual(1)](https://user-images.githubusercontent.com/76994465/104429394-d9526880-5585-11eb-947f-0f7d576aa4d9.png)

**Comment by samdog2727** [comment]
@CPTWilliamSE , that's what I'm talking about. The days that are skipped are days that do not have any data points, meaning the days that there are no applications or PIREPs filed.

**Comment by velocity23** [comment]
This is gonna require a fair bit of a rewrite but I'll make sure it comes in v1.2

**Comment by CPTWilliamSE** [comment]
@samdog2727 the issue I wanted to point out here is the graph sometimes is going back in time instead of a continuous progression to the current date. If you look closely at the images you'll see the dates jumping back and forth in time.

**Comment by velocity23** [comment]
Fixed in the next one, thanks for the report
