### ISSUE TITLE
ACARS Confirm Details

### ISSUE THREAD

**Issue by CPTWilliamSE** [va-net/flare#307]
**Is your feature request related to a problem? Please describe.**
Many of the details that the ACARS gathers are never presented to us.

**Describe the solution you'd like**
I'd like an additional prompt after you input your flight nr and fuel where all the flight details are presented at which point one could confirm or edit some of the details.

**Describe alternatives you've considered**
There's not really much.

**Comment by velocity23** [comment]
So like the fields it doesn't need could be disabled, but you still see them. Is that correct?

**Comment by CPTWilliamSE** [comment]
Yeah, that would be a good solution. I would like even being able to edit the fields ACARS fill's. Just in case it does something weird.

**Comment by velocity23** [comment]
Ok that shouldn't be too hard. Maybe this release, maybe next time.
