### ISSUE TITLE
ACARS Not Recognizing The Right Aircraft

### ISSUE THREAD

**Issue by CPTWilliamSE** [va-net/flare#309]
**Describe the bug**
Today I performed a flight and when it was completed I went to the ACARS page to file my PiRep. The ACARS found me but told me I was in an aircraft that we did not have in our fleet. I flew the SWISS A319. I then proceeded to delete the SWISS A319 from our fleet and added it again. The error still persisted. The error is still present after attempting to use ACARS at a later time. I suppose it's a simple error with the aircraft ID's not matching. This seems to be an issue with our entire fleet. Not just the A319.

**To Reproduce**
1. Perform a flight in any aircraft.
2. Click on ACARS and RUN ACARS.
4. See error.

**Expected behavior**
ACARS runs as it should without giving an error.

**Screenshots**
![Screenshot_2021-01-14 Operations Admin - Suisse Virtual](https://user-images.githubusercontent.com/76994465/104603658-ed2cc600-567c-11eb-82ff-e44c7dd7af37.png)
![Screenshot_2021-01-14 ACARS - Suisse Virtual](https://user-images.githubusercontent.com/76994465/104603677-f027b680-567c-11eb-9069-987641710e6a.png)

**Flare Version**
V1.1.2

**Comment by velocity23** [comment]
Might need access to your site for this one, I'll DM you on discord
