### ISSUE TITLE
Blank table when importing routes

### ISSUE THREAD

**Issue by CaptainGeorgeIF** [va-net/flare#311]
**Describe the bug**
When importing routes with the phpVMS Routes file, I only get a blank table with nothing in it.

**To Reproduce**
1. Go to 'Manage Routes'
2. Click on 'Import Routes'
3. Click on 'Process'
4. Follow the Import steps

**Expected behavior**
To have all the routes imported

**Screenshots**
![image](https://user-images.githubusercontent.com/50553084/105578293-5ac4aa80-5d7f-11eb-8368-c68469b5b26e.png)
![image](https://user-images.githubusercontent.com/50553084/105578321-8c3d7600-5d7f-11eb-9425-25422046eeb5.png)

**Flare Version**
Flare v1.2.0-beta4

**Additional context**

**Comment by velocity23** [comment]
Could you send me the full file that you're using on discord please?

**Comment by velocity23** [comment]
CSV file was invalid
