### ISSUE TITLE
Null on Codeshare Menu

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#321]
**Describe the bug**
Codeshare Menu has a red notification that reads "null"

**To Reproduce**
1. Go to 'Codeshare'
2. See error

**Expected behavior**
No notification unless codeshare request, then a one or two etc. if there is a codeshare request.

**Screenshots**
![image](https://user-images.githubusercontent.com/71337097/115117741-16a40900-9f6e-11eb-8d74-aa3417477cc1.png)

**Flare Version**
V.1.2.4-beta1

**Additional context**
Nope. Small issue, I believe it's an easy fix :)

**Comment by velocity23** [comment]
Fixed in the next one

**Comment by samdog2727** [comment]
This is still happening.

**Comment by samdog2727** [comment]
This is still happening @velocity23

**Comment by velocity23** [comment]
> This is still happening @velocity23 

Try clearing your cache
