### ISSUE TITLE
Error Connecting to VANet

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#322]
**Describe the bug**
When a pilot files a PIREP through "File PIREP", it does not go through and the pilot gets the error message "Error: There was an error connecting to VANet"

**To Reproduce**
Attempt to file a PIREP and see the error

**Expected behavior**
The PIREP to go through correctly with no complications

**Screenshots**
![image](https://user-images.githubusercontent.com/71337097/115147253-2d0e9b00-a028-11eb-8615-e434f58cf611.png)

**Flare Version**
V.1.2.4-beta2

**Additional context**
This happened in Beta 1 as well. 
This is a critical issue and it will be greatly appreciated if this could be fixed ASAP.
One pilot reported this error but no one else has attempted to file a PIREP on either of the betas so far.

**Comment by velocity23** [comment]
Jus FYI, this is what a beta is for. Yes it's a critical issue but you can expect those to come up because it's in testing and is not ready for release.
