### ISSUE TITLE
Negative Applications

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#323]
**Describe the bug**
On the Site Dashboard, the number of applications on the graph shows the possibility of having a negative value
**To Reproduce**

N/A

**Expected behavior**
Only positive values being possible

**Screenshots**
![Screen Shot 2021-04-18 at 9 34 42 AM](https://user-images.githubusercontent.com/71337097/115147528-54b23300-a029-11eb-9ab1-2acf8ce413f8.png)

**Flare Version**
V.1.2.4-beta2

**Additional context**
N/A

**Comment by velocity23** [comment]
Not something we can fix atm, the library I use for charts does this and I don't think there's anything I can do about it.
