### ISSUE TITLE
Minutes (0:XX) not displaying 

### ISSUE THREAD

**Issue by CR3WxSKULL** [va-net/flare#330]
**Describe the bug**
The minutes of flights are not being displayed on the Flare Crew Centre, or bots from Notifications of PIREPs

**To Reproduce**
1. Go to "PIREP Management" in the Admin panel
2. Click on "Manage PIREPs"
3. Look at any pending PIREPs
4. See no display of minutes 

**Expected behaviour**
Minutes should be displayed

**Screenshots**
<img width="971" alt="Screen Shot 2021-05-09 at 10 18 52 PM" src="https://user-images.githubusercontent.com/45743120/117594703-0c140400-b115-11eb-8f0e-c6b373179b53.png">

**Flare Version**
Flare v1.2.5 

**Additional context**
N/A

**Comment by velocity23** [comment]
Argh... this is what I get for not testing things properly. New update incoming.
