### ISSUE TITLE
Custom Profile Pictures For Pilots

### ISSUE THREAD

**Issue by CaptainZac1** [va-net/flare#334]
**Is your feature request related to a problem? Please describe.**
Pilots can set a profile picture to their account.￼ similar to the system tha￼t something like VABase uses. 

**Describe the solution you'd like**
On the account settings page, a pilot can import a photo of a profile picture they would want, and that profile picture can appear next to their name in places where it can.￼

**Describe alternatives you've considered**
A pilot can select an icon from a list to appear next to their name, rather than uploading their own photo.￼

￼

**Comment by velocity23** [comment]
Profile photos can be a security risk, as people can choose malicious photos which run a script in the browser or things like that, and the malicious parts are difficult to strip out. I can look into this nevertheless.

**Comment by CR3WxSKULL** [comment]
This would be a good idea if forum sign-in were to come one day. What your IFC profile picture is is your flare CC profile picture. Like for VANet when you sign-in with google your profile picture on VANet is whatever your google profile picture is

**Comment by velocity23** [comment]
@CR3WxSKULL We're planning on adding a 'Sign In with VANet' option that may include profile picture, depending on how everything goes
