### ISSUE TITLE
SimBrief Integration

### ISSUE THREAD

**Issue by CaptainZac1** [va-net/flare#335]
**Is your feature request related to a problem? Please describe.**
So, I don't know how possible this is, but I would like to see an integration with simbrief ￼one day. I know they have an API system, so I think it's possible even though it may be complicated.￼

**Describe the solution you'd like**
When a pilot looks at the details for a flight (when they click the + to expand it), they will automatically get the waypoints needed to fly it. ￼

**Describe alternatives you've considered**
None really, unless there is another system that does this.

**Comment by velocity23** [comment]
I've talked to Chris from FPLtoIF about a possible integration with his system, I can try reaching out again
