### ISSUE TITLE
ACARS "You're Flying an Aircraft that isn't in this VA's Fleet!"

### ISSUE THREAD

**Issue by CPTWilliamVM** [va-net/flare#336]
**Describe the bug**
When filing an ACARS PiRep the "You're Flying an Aircraft that isn't in this VA's Fleet!" message appears

**To Reproduce**
1. Go to 'ACARS'
2. Click on 'Run ACARS'
3. See error

**Expected behavior**
Flight is found and details are loaded.

**Screenshots**
![Screenshot_2021-05-24 ACARS - Suisse Virtual](https://user-images.githubusercontent.com/50374642/119352047-78f4d580-bca1-11eb-87b5-1e2bdcdbb663.png)

**Flare Version**
Flare v1.2.6

**Additional context**
Error is reproducable on both live and test sites. The aircraft have been removed and re-entered but doesnt help. The error is not limited to one aircraft. I have tried multiple aircraft and they all failed.

**Comment by velocity23** [comment]
Fixed in the next one
