### ISSUE TITLE
Cannot See Callsign When Approving PIREPs

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#347]
**Describe the bug**
When approving PIREPs, the callsign field is no longer visible as it was before the beta. I really need that to see who filed what.

**To Reproduce**
N/A

**Expected behavior**
The callsign field to be shown on that page.

**Screenshots**
N/A

**Flare Version**
Beta 2.0.0

**Additional context**
Probably an easy fix.

**Comment by velocity23** [comment]
I removed it because it was built badly, but I've rebuilt that part of things for the next release to put it back and make it faster than before.
