### ISSUE TITLE
Coded Widgets for Websites **PLUGIN** (like VAbase, icrewcenters, etc.)

### ISSUE THREAD

**Issue by American1345Super** [va-net/flare#353]
Hi, @velocity23 I think you told me to put this here so you did not forget. 

I have seen the widgets that show "29498 hours flown" "49583 total pilots" and more. I understand most other CCs have their own websites to go along but some don't. They have coded widgets or embed widgets that link to their crew center. They do not just show numbers of pilots or miles flown, they also show recently joined pilots, and recent PIREPs as well as new codeshare partners. 

I love Flare and with this new update coming, I think this new plugin along with the rest will be an amazing addition. I thin this would be similar to the already existing "Slack/Discord Notifications" plugin. I also HOPE it comes with HTML, CSS, and JS options for code since all our VA websites are mostly different. 
**Additional context**

Anyways, I hope this is considered as an addition to Flare. Besides that, great job @velocity23 ! Keep up the good work.

Best,

American

**Comment by velocity23** [comment]
Please open a new issue using the template provided
