### ISSUE TITLE
Application Submission Bug

### ISSUE THREAD

**Issue by American1345Super** [va-net/flare#363]
Applications will not be submitted - this is due to a bug I believe. This can be recreated by submitting an application and checking the admin panel. This should be fixed before the main software release.

**Comment by American1345Super** [comment]
So I need to go on to My PHP Admin?

**Comment by velocity23** [comment]
No, when you create an issue you must use the template provided to you instead of deleting it all. There are fields you have to fill out like description, version, steps to reproduce, etc.
