### ISSUE TITLE
Neutral ICAO Fill-in Examples

### ISSUE THREAD

**Issue by CR3WxSKULL** [va-net/flare#369]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Instead of ICAO examples such as "YSSY", have them set to "ICAO" to remain neutral for all VA's

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by velocity23** [comment]
Is this in the Tailwind theme?

**Comment by CR3WxSKULL** [comment]
Yes on the tailwind. I don’t believe the default even has examples for what to fill in if I’m not mistaken
