### ISSUE TITLE
HR/Tech Support Submission on Flare

### ISSUE THREAD

**Issue by AviatorMan** [va-net/flare#371]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This would be for users to submit a message to the HR Manager. THIS SHOULD FOR SURE BE ADDED, and is very important for users to stay in contact with their HR. The other option would echo the same system but the only difference would be that it would be for tech support. 

**Describe alternatives you've considered**
Google Form in the custom menu bar, however, it is hard to manage so many different forms, and it would be easier if it was in one crew center for the HR to view. Same thing with tech support, except only the tech support will be able to view it.

**Comment by velocity23** [comment]
No, sorry. This isn't the purpose of Flare.
