### ISSUE TITLE
Aircraft List Not Displaying

### ISSUE THREAD

**Issue by CR3WxSKULL** [va-net/flare#378]
### Bug Description

Aircraft list does not display when selecting the "Aircraft" filter for route searches. 

### Steps to Reproduce

1. Go to "Route Database";
2. Under the "Aircraft" field, select "Any Aircraft" dropdown; then
3. See list of "()'

### Expected Behavior

Each aircraft in a VAs fleet should display

### Flare Version

v2.0.0-beta

### Additional Information

<img width="1028" alt="Screen Shot 2021-07-27 at 3 30 07 AM" src="https://user-images.githubusercontent.com/45743120/127106575-f92e8e09-98a3-4c64-9d26-0099d87d3407.png">

_Image above shows the displaying issue of aircraft in a VAs fleet_

**Comment by velocity23** [comment]
Is this only on the default theme or Tailwind too?

**Comment by CR3WxSKULL** [comment]
Literally forgot to put it, lol. 

This is the default theme
