### ISSUE TITLE
Alert Doesn't Show Up

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#381]
### Bug Description

When you look from both the tailwind and from the default theme (this is when you are already in the admin area on the tailwind theme), the red notification with a number signaling the number of PIREPs that have not been accepted or denied is no longer there even when PIREPs are.

### Steps to Reproduce

1. Make sure PIREPs have been filed
2. Click on PIREP Management
3. See Error

### Expected Behavior

A red square thing that has the number of PIREPs not approved shown.

### Flare Version

v2.0.0-beta

### Additional Information

I have not checked if this happens on the default theme. I am not sure if this is a huge issue as we are working to move away from the default theme in the Admin section. I just wanted to make you aware.

**Comment by velocity23** [comment]
I'm aware of that issue in the Tailwind-themed pages, but is it not working in the default-themed admin pages either? Have you tried clearing the site cache in **Site Settings > Maintenance**?
