### ISSUE TITLE
Active ATC System Bug

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#403]
### Bug Description

In the "Active ATC" screen, the header for "Controller" is missing.

### Steps to Reproduce

See the error on the home page where Active ATC is shown (Tailwind)

### Expected Behavior

The "Controller" or "User" header to be there

### Flare Version

v2.0.0-beta

### Additional Information

![Screen Shot 2021-08-18 at 1 56 00 PM](https://user-images.githubusercontent.com/71337097/129948245-97e1cbcf-c607-4e88-9f9f-515d4ddb0231.png)

Here is what it looks like now.

**Comment by velocity23** [comment]
Clear your browser cache, I made a change to one of the scripts so that it should now look like this

![image](https://user-images.githubusercontent.com/34199284/129979527-0e1782c1-47b0-4d4f-9990-9806034adc7b.png)
