### ISSUE TITLE
Cannot Sign Up For Gates

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#406]
### Bug Description

Now that you can post events, there is a new issue: you cannot sign up for the event. When you press "Sign Up", it says "Updating, please wait" and it does nothing, even after you refresh.

### Steps to Reproduce

1. View an event
2. Click "Sign Up"
3. See Pop-Up message
4. Reload page and see that nothing happens

### Expected Behavior

You should be in a Gate for the event.

### Flare Version

v2.0.0-beta

**Comment by velocity23** [comment]
Is this on the Tailwind theme?

**Comment by samdog2727** [comment]
Yes it is, @velocity23 .

**Comment by velocity23** [comment]
Unable to reproduce, can you send a screen recording?

**Comment by samdog2727** [comment]
![Screen Shot 2021-08-24 at 8 21 26 AM](https://user-images.githubusercontent.com/71337097/130615539-17d69c29-b2fb-49aa-bebc-3ce99ebff185.png)

**Comment by samdog2727** [comment]
https://user-images.githubusercontent.com/71337097/130615971-0cbf501a-1a1a-4fe5-97c3-196989b5865a.MP4

**Comment by velocity23** [comment]
Free host issue
