### ISSUE TITLE
Admin Events page fails to load events

### ISSUE THREAD

**Issue by sam2875** [va-net/flare#425]
### Bug Description

The table on the Admin Events page simply displays 'Loading' and fails to display any events

### Steps to Reproduce

1. Create at least 1 event
2. Go to Events on the Admin Panel
3. Note that no events are displayed, it simply says 'Loading...'

### Expected Behavior

I expected events to populate the table

### Flare Version

v2.0.0

**Comment by joshhicks1** [comment]
I am experiencing this issue too.

**Comment by velocity23** [comment]
> I am experiencing this issue too.

Thanks Josh 🙃

**Comment by velocity23** [comment]
Should be fixed

**Comment by joshhicks1** [comment]
This is fixed now but you can no longer edit events, it gives an error since it doesn't save the aircraft

**Comment by velocity23** [comment]
Can you open a new issue?
