### ISSUE TITLE
Aircraft Liveries Do Not Load

### ISSUE THREAD

**Issue by Bears-Beets-BSG** [va-net/Flare#43]
# Describe the issue

When adding aircraft to fleet, liveries do not load for any aircraft selected.

# Steps to reproduce the issue

Manage Fleet --> Add Aircraft

# Screenshots

![liveries-not-loading](https://user-images.githubusercontent.com/50090529/90968821-00b57580-e4bf-11ea-8c63-fcb759db4a71.png)

**Comment by Velocity23** [comment]
Let's add a disabled loading option as it can take time
