### ISSUE TITLE
Keep me logged in

### ISSUE THREAD

**Issue by joshhicks1** [va-net/flare#432]
**Is your feature request related to a problem? Please describe.**
Users keep being logged out when returning to the site.

**Describe the solution you'd like**
Extending the user session to keep them logged in so they don't need to sign in every time

**Describe alternatives you've considered**
Storing cookies for longer periods? Not really sure what the best way to achieve this is

**Additional context**

**Comment by velocity23** [comment]
This is... not as easy as it sounds. Will keep it open for now but unfortunately it's a bit too much for v2.1
