### ISSUE TITLE
Unable to edit existing routes

### ISSUE THREAD

**Issue by AerLingusVA** [va-net/flare#433]
### Bug Description

Once a route has been added to the route database, should I wish to edit that route I am unable to do so from the Manage Routes screen. The edit link is present, but does not link/load anything.

### Steps to Reproduce

1. Add a route to the route database
2. Head to Operations Management > Route Management
3. Click on the edit button in the action column for any route

### Expected Behavior

A route edit modal to appear

### Flare Version

v2.1.0-beta

**Comment by velocity23** [comment]
Thanks for these reports, will get them fixed ASAP
