### ISSUE TITLE
No Edit Option For Fleet

### ISSUE THREAD

**Issue by Bears-Beets-BSG** [va-net/flare#44]
# Describe the issue

Cannot edit aircraft already added to fleet. If deletion is the only option, would it affect anything else if a modification needs to be made by deletion and re-adding?

# Screenshots

![fleet-works-no-edit](https://user-images.githubusercontent.com/50090529/90968832-293d6f80-e4bf-11ea-8d08-5ba563d27eeb.png)

**Comment by rebal15** [comment]
@Velocity23 the aircraft is not deleted, it is simply marked as inactive in the database. It can always be re-added again, so I think this should be kept. I'll get editable aircraft done though.
