### ISSUE TITLE
Events stick around after it has started

### ISSUE THREAD

**Issue by joshhicks1** [va-net/flare#440]
**Is your feature request related to a problem? Please describe.**
Events disappear from the list as soon as it reaches the start time

**Describe the solution you'd like**
It would be nice if it didn't disappear immediately so people could still access the event after it has started to see event info (obviously they can still get to it via a link but it would be nice if they could access it without it)

**Describe alternatives you've considered**
This sounds like a VANet thing so no

**Comment by velocity23** [comment]
Will fix this for v3
