### ISSUE TITLE
Page

### ISSUE THREAD

**Issue by Baba-IF** [va-net/flare#443]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It's can be really cool if this can be added.

**Describe alternatives you've considered**

No one.

**Additional context**

So the idea is here to create a plug-in or something like that can allow us to post page, it's another things than the news thing. It's kinda something like blog posts.

**Comment by Adrian-KI** [comment]
This with integration to discord would be amazing.

**Comment by BaptisteDesmet** [comment]
> This with integration to discord would be amazing.

Yes, that's true. Didn't think about.
