### ISSUE TITLE
Event Plugin 

### ISSUE THREAD

**Issue by Baba-IF** [va-net/flare#447]
### Bug Description

I think there is a problem with the event plug-in more specifically to show the gate available for the event. When I try to add gate for the event it doesn’t work same if I use the comma, it’s still not working.

### Steps to Reproduce

1. Go to the Crew Center.
2. Go to the event manager.
3. Create a `Test` event.
4. Add gate properly.
5. Go to the `events` on the sidebar.
6. Click on the event you want to go to.

### Expected Behavior

See the full gate list that are available for the event.

### Flare Version

v2.1.1-beta

**Comment by velocity23** [comment]
Unable to reproduce
