### ISSUE TITLE
New Routes Not Listed

### ISSUE THREAD

**Issue by Bears-Beets-BSG** [va-net/Flare#45]
# Describe the issue

Message says a new route is successfully added, but only the first ever added route shows up in the list.

# Steps to reproduce the issue

Routes Management --> Add Route

# Screenshots

![routes-management-before](https://user-images.githubusercontent.com/50090529/90968879-a5d04e00-e4bf-11ea-8043-30ab62be2410.png)
![routes-management-after](https://user-images.githubusercontent.com/50090529/90968881-a668e480-e4bf-11ea-8e65-2476d93431d8.png)

**Comment by Velocity23** [comment]
I can't even add routes. You might have to have a look at this one @rebal15.
