### ISSUE TITLE
Unable to add/edit route notes

### ISSUE THREAD

**Issue by EvanV17** [va-net/flare#464]
### Bug Description

Unable to add and edit route notes on the Tailwind theme

### Steps to Reproduce

1. Open route management tab
2. Click any route (with or without a route note)
3. Observe no field to add/edit route

### Expected Behavior

Able to add/edit route note

### Flare Version

v2.3.0

### Additional Information

Tailwind theme only; version actually v2.4.0

**_IMAGES_**

<img width="1158" alt="Screenshot 2022-04-16 at 9 08 56 AM" src="https://user-images.githubusercontent.com/45743120/163674380-6a3fd10d-ac84-4b96-ace5-dd360f7f4755.png">
<img width="1119" alt="Screenshot 2022-04-16 at 9 08 41 AM" src="https://user-images.githubusercontent.com/45743120/163674382-d1353c9d-e683-4db7-84a0-b12831113419.png">

**Comment by velocity23** [comment]
Fixed in the next one
