### ISSUE TITLE
Deleting a multiple creates a new one

### ISSUE THREAD

**Issue by EvanV17** [va-net/flare#465]
### Bug Description

Deleting a multiplier creates a new one with 0x worth and no name. 

Sometimes, the multiplier you intended to delete does not delete at all.

### Steps to Reproduce

1. Open manage multipliers
2. Delete a multiplier 
3. See new multiplier with 0x and no name

### Expected Behavior

Deletes with no issue

### Flare Version

v2.3.0

### Additional Information

Tailwind v2.4.0. Previous issue:

https://github.com/va-net/flare/issues/456

**Comment by velocity23** [comment]
Unable to reproduce. I'll push the file in this update in case there's an error there.
