### ISSUE TITLE
Flight Time Format

### ISSUE THREAD

**Issue by Bears-Beets-BSG** [va-net/Flare#47]
# Describe the issue

Flight time format is actually time format instead of duration.

# Screenshots

![flight-time-1](https://user-images.githubusercontent.com/50090529/90969032-8df9c980-e4c1-11ea-90fd-38a2973abf05.png)
![flight-time-2](https://user-images.githubusercontent.com/50090529/90969033-8df9c980-e4c1-11ea-8810-f3a1b4ba07df.png)

**Comment by Velocity23** [comment]
Gonna handball this one to you @rebal15, the flight time will need to be split into hour and minute fields, preferably in a column that stacks on mobile (`col-sm-6`).

**Comment by Velocity23** [comment]
Never mind, should actually be fairly simple
