### ISSUE TITLE
Categorize All Admin Functions

### ISSUE THREAD

**Issue by Velocity23** [va-net/flare#50]
Currently only Operations is under a dropdown, to make the design more unified could we categorize all admin menu items?

**Comment by Velocity23** [comment]
@rebal15 I need #49 and #61 fixed before I can work on this

**Comment by rebal15** [comment]
> @rebal15 I need #49 and #61 fixed before I can work on this

I'll do that today @Velocity23

**Comment by rebal15** [comment]
@Velocity23 any progress on this?

**Comment by Velocity23** [comment]
Not yet. I’ll work on it tomorrow.
