### ISSUE TITLE
Make Edit Staff Model run on JS

### ISSUE THREAD

**Issue by Velocity23** [va-net/flare#55]
Edit Staff modals are done individually instead of via attributes and jQuery. Instead, use jQuery like the edit user modals. This will also fix #41

**Comment by rebal15** [comment]
Would you be able to do this one @Velocity23?

**Comment by Velocity23** [comment]
> Would you be able to do this one @Velocity23?

Sure thing!

**Comment by Velocity23** [comment]
Due to permissions management, it's too hard to make it work
