### ISSUE TITLE
PIREP Setup not working

### ISSUE THREAD

**Issue by alanshaji200** [va-net/flare#60]
# Describe the issue

Unable to setup PIREPs by clicking on "I have spawned in on the casual server" (Update.php file does not work)

# Steps to reproduce the issue

Left-hand sidebar > File PIREP > "I have spawned in on the casual server" > New tab opens with error 500

# Screenshots

N/A

**Comment by rebal15** [comment]
Hmm, that's a strange one, it seems to be working for me. Could you try downloading the latest updates by downloading straight from the [master](https://github.com/va-net/Flare/tree/master) branch? Let me know if it still occurs. @alanshaji200

**Comment by alanshaji200** [comment]
It has been fixed now, thanks.
