### ISSUE TITLE
Cannot login after latest update

### ISSUE THREAD

**Issue by alanshaji200** [va-net/Flare#83]
# Describe the issue

Unable to login after installation of latest update. The login screen at /index.php just resets once credentials are submitted. No error messages appear.

# Steps to reproduce the issue

Download & Upload latest Master update > replace config file with backup > Try to login > page refreshes

# Screenshots

N/A

**Comment by alanshaji200** [comment]
I realised this can be fixed by going to classes/Hash.php and change where it says PASSWORD_ARGON2ID to PASSWORD_DEFAULT

**Comment by rebal15** [comment]
All done @alanshaji200
