### ISSUE TITLE
Add 2-Factor-Authentication

### ISSUE THREAD

**Issue by velocity23** [va-net/flare#97]
See [here](https://medium.com/@richb_/easy-two-factor-authentication-2fa-with-google-authenticator-php-108388a1ea23). Should include the functionality to require 2FA for admins as an option.

**Comment by gayblackpeoplearepoo** [comment]
i will take u to bed

**Comment by TheWheelDaddy** [comment]
@Velocity23 
Feature Request: 
Hubs on flare to consolidate pilots!

**Comment by velocity23** [comment]
https://github.com/sonata-project/GoogleAuthenticator
https://medium.com/@richb_/easy-two-factor-authentication-2fa-with-google-authenticator-php-108388a1ea23

**Comment by velocity23** [comment]
Closing (again) in favor of a Sign in with VANet button
